#!/usr/bin/env php
<?php

use dimichspb\messagebird\ConsoleApplication;

require_once (__DIR__ . '/src/bootstrap.php');

$configFilePath = __DIR__;
$configFileName = 'config.ini';
$localConfigFileName = 'config-local.ini';

$application = createApplication(
    ConsoleApplication::class,
    $configFilePath,
    $configFileName,
    $localConfigFileName
);

$application->run();